### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by rolipobi** [ljyloo/LevelDb2Avnil#20]
I always get this error: 

D:\mc\LevelDb2Avnil-master (1)\LevelDb2Avnil-master>java -jar Converter.jar world worldanvil
Exception in thread "main" java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(Unknown Source)
        at org.iq80.leveldb.util.Zlib$ByteBufferBackedOutputStream.write(Zlib.java:91)
        at org.iq80.leveldb.util.Zlib$ZLibSPI.copy(Zlib.java:108)
        at org.iq80.leveldb.util.Zlib$ZLibSPI.uncompress(Zlib.java:118)
        at org.iq80.leveldb.util.Zlib.uncompress(Zlib.java:181)
        at org.iq80.leveldb.table.MMapTable.readBlock(MMapTable.java:121)
        at org.iq80.leveldb.table.Table.openBlock(Table.java:79)
        at org.iq80.leveldb.util.TableIterator.getNextBlock(TableIterator.java:102)
        at org.iq80.leveldb.util.TableIterator.getNextElement(TableIterator.java:79)
        at org.iq80.leveldb.util.AbstractSeekingIterator.hasNext(AbstractSeekingIterator.java:48)
        at org.iq80.leveldb.util.InternalTableIterator.getNextElement(InternalTableIterator.java:51)
        at org.iq80.leveldb.util.AbstractSeekingIterator.hasNext(AbstractSeekingIterator.java:48)
        at org.iq80.leveldb.util.DbIterator.resetPriorityQueue(DbIterator.java:155)
        at org.iq80.leveldb.util.DbIterator.<init>(DbIterator.java:75)
        at org.iq80.leveldb.impl.DbImpl.internalIterator(DbImpl.java:781)
        at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:747)
        at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:738)
        at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:84)
        at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:66)
        at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:37)

Any idea?

**Comment by ljyloo** [comment]
Seems like your map is too big for your memory. May I ask the size of the map and your computer memory?

**Comment by rolipobi** [comment]
PC has 16GB Ram, the MAP has 6GB. How can I modify the script that it works?

**Comment by ljyloo** [comment]
Maybe you don't allocate enough memory for java VM? Try this one
`java -Xms10240m -Xmx10240m -jar Converter.jar world worldanvil`

**Comment by rolipobi** [comment]
its the same.

**Comment by ljyloo** [comment]
I've never been dealing with such a huge map XD... If you don't mind can you send me your map? I need to do some experiment

**Comment by ljyloo** [comment]
You can send me link privately via twitter message @ljyloo

**Comment by ljyloo** [comment]
OK……I get it. The converter you are using is for converting Pocket Edition(PE) map to PC map……And you want to use it to convert your PC map to PE map…… Read the README first

**Comment by rolipobi** [comment]
thanks for the info. It is not easy to find the right thing, because the name is always equal (leveldb).
I would need it from Windows 10 Edition (C++ leveldb) to pocketmine server. 
where can I get the right converter?

**Comment by ljyloo** [comment]
Wait, you are playing Minecraft Windows 10 Edition? That's using the same format(LevelDb) as the Pocket Edition. And my converter should do the job XD, but it failed. Can you send me your map to find out the bug, thanks.

**Comment by ljyloo** [comment]
The PC edition I am talking about is the JAVA edition

**Comment by thebigsmileXD** [comment]
@rolipobi pocketmine in pmmp/PocketMine-MP actually can load these  fully working soon. ´The last change was 10 days ago: https://github.com/pmmp/PocketMine-MP/commit/b4a149cce81bfce22bb57e07554946620ecb2f74#diff-0

Maybe try setting default level type to Leveldb in the properties.yml. As far as i remember leveldb would requiere an php extension which exists here: https://github.com/pmmp/php-leveldb/releases

**Comment by rolipobi** [comment]
I set the format to leveldb in properties.yml. but it won`t work. when I start it, the folder "region" is generated :-(

**Comment by rolipobi** [comment]
Nobody who can help me?

**Comment by ljyloo** [comment]
*Sigh* I told you to send me your map :|

**Comment by dawinSoft** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.pf0, @unsunset, @njzydark, @osama-ata, @dreamerlzl, @Eloco, @freshSep, @rqx9, @lennyluosz, @chen-bliss, @Jsffyayoi, @yaserabdelaziz, @firstrose, @Bastiaantjuhh, @yanwuxiao, @codthing, @h0kd33, @jdcaballerov, @adambillcooper, @vesche
