### ISSUE TITLE
No Such Element Exception...

### ISSUE THREAD

**Issue by philapollo** [ljyloo/LevelDb2Avnil#25]
Hi there, I get quite a few unknown key like the one below (not sure if this is a problem) but the iterator eventually runs into the exception below.
cheers,
Phil

Unknown Key: 
0x126 108 111 099 097 108 095 112 108 097 121 101 114 

Unknown Key: gacy chunk X: -1 Z: -108
0x-01 -01 -01 -01 -01 -01 -01 -01 118 

Exception in thread "main" java.util.NoSuchElementException
	at org.iq80.leveldb.util.AbstractSeekingIterator.next(AbstractSeekingIterator.java:59)
	at org.iq80.leveldb.impl.SeekingIteratorAdapter.next(SeekingIteratorAdapter.java:60)
	at org.iq80.leveldb.impl.SeekingIteratorAdapter.next(SeekingIteratorAdapter.java:28)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:131)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:37)

**Comment by misssalad612** [comment]
Do you use the Converter.jar?

**Comment by misssalad612** [comment]
I have upload a new one which should be more stable and less bugs, So please give it a try :)
