### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by Mario3264** [ljyloo/LevelDb2Avnil#28]
When I try to convert a world, this happens:

`Exception in thread "main" java.lang.NullPointerException
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:198)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:34)
`

**Comment by Mario3264** [comment]
It doesn't happen anymore in the latest version.
