### ISSUE TITLE
Exceptions generated when converting world on three different OS's

### ISSUE THREAD

**Issue by draganlazin** [ljyloo/LevelDb2Avnil#29]
Hello,

I've been trying to convert a world, however I get exceptions each time. In Windows 7x64 with Javax64:

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.iq80.leveldb.util.Slice.<init>(Slice.java:53)
	at org.iq80.leveldb.util.Slices.allocate(Slices.java:89)
	at org.iq80.leveldb.util.Slices.copiedBuffer(Slices.java:110)
	at org.iq80.leveldb.table.MMapTable.readBlock(MMapTable.java:122)
	at org.iq80.leveldb.table.Table.openBlock(Table.java:79)
	at org.iq80.leveldb.util.TableIterator.getNextBlock(TableIterator.java:102)
	at org.iq80.leveldb.util.TableIterator.getNextElement(TableIterator.java:79)
	at org.iq80.leveldb.util.AbstractSeekingIterator.hasNext(AbstractSeekingIterator.java:48)
	at org.iq80.leveldb.util.InternalTableIterator.getNextElement(InternalTableIterator.java:51)
	at org.iq80.leveldb.util.AbstractSeekingIterator.hasNext(AbstractSeekingIterator.java:48)
	at org.iq80.leveldb.util.LevelIterator.getNextElement(LevelIterator.java:109)
	at org.iq80.leveldb.util.AbstractSeekingIterator.hasNext(AbstractSeekingIterator.java:48)
	at org.iq80.leveldb.util.DbIterator$ComparableIterator.next(DbIterator.java:253)
	at org.iq80.leveldb.util.DbIterator.getNextElement(DbIterator.java:122)
	at org.iq80.leveldb.util.AbstractSeekingIterator.hasNext(AbstractSeekingIterator.java:48)
	at org.iq80.leveldb.impl.SnapshotSeekingIterator.findNextUserEntry(SnapshotSeekingIterator.java:80)
	at org.iq80.leveldb.impl.SnapshotSeekingIterator.getNextElement(SnapshotSeekingIterator.java:72)
	at org.iq80.leveldb.util.AbstractSeekingIterator.hasNext(AbstractSeekingIterator.java:48)
	at org.iq80.leveldb.impl.SeekingIteratorAdapter.hasNext(SeekingIteratorAdapter.java:54)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:85)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:34)

--------------------------------------------------

In OS X and Linux:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 7
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:88)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:34)
----------------------------------------------------

I downloaded the zip package today, Aug 22, 2017.

**Comment by misssalad612** [comment]
For the latter exception, I am working on it. May I ask how many memory did you give JVM and how big the world file was?

**Comment by ljyloo** [comment]
@misssalad612 Your code contains a loop inside a loop, which i think is unnecessary

**Comment by misssalad612** [comment]
@ljyloo hmm... you are right. The code should be more direct.

**Comment by ljyloo** [comment]
@misssalad612 thanks you for helping me update the project i am busy at my work:)

**Comment by Murphy2002** [comment]
I have the same issue could someone help me?
