### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by bwburnsides** [ljyloo/LevelDb2Avnil#31]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 7
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:88)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:34)

**Comment by misssalad612** [comment]
Oops, I forgot to update the jar file.
