### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by nnnlog** [ljyloo/LevelDb2Avnil#33]
```
Exception in thread "main" java.lang.IllegalStateException: CURRENT file does not end with newline
	at org.iq80.leveldb.impl.VersionSet.recover(VersionSet.java:340)
	at org.iq80.leveldb.impl.DbImpl.<init>(DbImpl.java:187)
	at org.iq80.leveldb.impl.Iq80DBFactory.open(Iq80DBFactory.java:71)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:63)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:36)
```

**Comment by Syndaryl** [comment]
I am also getting this error.

**Comment by TheMMcOfficial** [comment]
same for a 1.5.2 world
