### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by MinecraftWhiz04** [ljyloo/LevelDb2Avnil#35]
Exception in thread "main" org.iq80.leveldb.shaded.guava.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.get(LocalCache.java:3937)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.iq80.leveldb.impl.TableCache.getTable(TableCache.java:91)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:79)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:74)
	at org.iq80.leveldb.impl.Version.getLevel0Files(Version.java:146)
	at org.iq80.leveldb.impl.DbImpl.internalIterator(DbImpl.java:781)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:747)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:738)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:84)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:65)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:36)
Caused by: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.CompressionType.getCompressionTypeByPersistentId(CompressionType.java:34)
	at org.iq80.leveldb.table.BlockTrailer.readBlockTrailer(BlockTrailer.java:96)
	at org.iq80.leveldb.table.MMapTable.readBlock(MMapTable.java:95)
	at org.iq80.leveldb.table.Table.<init>(Table.java:61)
	at org.iq80.leveldb.table.MMapTable.<init>(MMapTable.java:48)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:127)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:114)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:67)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:62)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 13 more

**Comment by Murphy2002** [comment]
I have the same issue.

**Comment by reense** [comment]
Same here.

**Comment by misssalad612** [comment]
#34

**Comment by KerbalFun123** [comment]
Me too

**Comment by BrBarry** [comment]
and again

**Comment by Redherring9** [comment]
Seems this is broken :(
