### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/ljyloo/PE2PC/PE2PC : Unsupported major.minor version 52.0 

### ISSUE THREAD

**Issue by iblowmymind** [ljyloo/LevelDb2Avnil#40]
What is this error? Running OSX 10.12.6. 

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/ljyloo/PE2PC/PE2PC : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

Have to use Legacy Java 6 because java command line doesn't work with Java 8.

**Comment by Mario3264** [comment]
It is an error due to the fact that you need Java 8 for it to work, since it probably is compiled using Java 8. You can't use Java 6 for it.

**Comment by iblowmymind** [comment]
Oh. I've learned some things new a few months ago. I'll link my Java 8 JRE to /usr/local/bin.
