### ISSUE TITLE
Main thread UncheckedExecutionException

### ISSUE THREAD

**Issue by hendryhu** [ljyloo/LevelDb2Avnil#44]
I was trying to convert but then this happens.

Exception in thread "main" java.io.FileNotFoundException: world\db\MANIFEST-000016 (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.iq80.leveldb.impl.VersionSet.recover(VersionSet.java:345)
	at org.iq80.leveldb.impl.DbImpl.<init>(DbImpl.java:187)
	at org.iq80.leveldb.impl.Iq80DBFactory.open(Iq80DBFactory.java:71)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:63)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:36)

I looked and saw that my manifest file ended in mp4a, which was weird, so I got rid of the file extension and got this:

Exception in thread "main" org.iq80.leveldb.shaded.guava.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.get(LocalCache.java:3937)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.iq80.leveldb.impl.TableCache.getTable(TableCache.java:91)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:79)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:74)
	at org.iq80.leveldb.impl.Version.getLevel0Files(Version.java:146)
	at org.iq80.leveldb.impl.DbImpl.internalIterator(DbImpl.java:781)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:747)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:738)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:84)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:65)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:36)
Caused by: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.CompressionType.getCompressionTypeByPersistentId(CompressionType.java:34)
	at org.iq80.leveldb.table.BlockTrailer.readBlockTrailer(BlockTrailer.java:96)
	at org.iq80.leveldb.table.MMapTable.readBlock(MMapTable.java:95)
	at org.iq80.leveldb.table.Table.<init>(Table.java:61)
	at org.iq80.leveldb.table.MMapTable.<init>(MMapTable.java:48)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:127)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:114)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:67)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:62)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 13 more

**Comment by dac1976** [comment]
I'm getting something similar when i try converting both MCPE worlds from iOS and from Windows Edition:

Exception in thread "main" org.iq80.leveldb.shaded.guava.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.get(LocalCache.java:3937)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.iq80.leveldb.impl.TableCache.getTable(TableCache.java:91)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:79)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:74)
	at org.iq80.leveldb.util.LevelIterator.openNextFile(LevelIterator.java:137)
	at org.iq80.leveldb.util.LevelIterator.getNextElement(LevelIterator.java:113)
	at org.iq80.leveldb.util.AbstractSeekingIterator.hasNext(AbstractSeekingIterator.java:48)
	at org.iq80.leveldb.util.DbIterator.resetPriorityQueue(DbIterator.java:160)
	at org.iq80.leveldb.util.DbIterator.<init>(DbIterator.java:75)
	at org.iq80.leveldb.impl.DbImpl.internalIterator(DbImpl.java:781)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:747)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:738)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:84)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:65)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:36)
Caused by: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.CompressionType.getCompressionTypeByPersistentId(CompressionType.java:34)
	at org.iq80.leveldb.table.BlockTrailer.readBlockTrailer(BlockTrailer.java:96)
	at org.iq80.leveldb.table.MMapTable.readBlock(MMapTable.java:95)
	at org.iq80.leveldb.table.Table.<init>(Table.java:61)
	at org.iq80.leveldb.table.MMapTable.<init>(MMapTable.java:48)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:127)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:114)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:67)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:62)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 17 more
Exception in thread "main" org.iq80.leveldb.shaded.guava.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.get(LocalCache.java:3937)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.iq80.leveldb.impl.TableCache.getTable(TableCache.java:91)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:79)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:74)
	at org.iq80.leveldb.util.LevelIterator.openNextFile(LevelIterator.java:137)
	at org.iq80.leveldb.util.LevelIterator.getNextElement(LevelIterator.java:113)
	at org.iq80.leveldb.util.AbstractSeekingIterator.hasNext(AbstractSeekingIterator.java:48)
	at org.iq80.leveldb.util.DbIterator.resetPriorityQueue(DbIterator.java:160)
	at org.iq80.leveldb.util.DbIterator.<init>(DbIterator.java:75)
	at org.iq80.leveldb.impl.DbImpl.internalIterator(DbImpl.java:781)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:747)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:738)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:84)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:65)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:36)
Caused by: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.CompressionType.getCompressionTypeByPersistentId(CompressionType.java:34)
	at org.iq80.leveldb.table.BlockTrailer.readBlockTrailer(BlockTrailer.java:96)
	at org.iq80.leveldb.table.MMapTable.readBlock(MMapTable.java:95)
	at org.iq80.leveldb.table.Table.<init>(Table.java:61)
	at org.iq80.leveldb.table.MMapTable.<init>(MMapTable.java:48)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:127)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:114)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:67)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:62)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 17 more

**Comment by garvord** [comment]
I am experiencing the same error code, when trying to convert a MCPE world.
Platform: Up to date. MCPE 1.2.13, Windows 10 x64, Java 8, update 162.

Exception in thread "main" org.iq80.leveldb.shaded.guava.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.get(LocalCache.java:3937)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.iq80.leveldb.impl.TableCache.getTable(TableCache.java:91)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:79)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:74)
	at org.iq80.leveldb.util.LevelIterator.openNextFile(LevelIterator.java:137)
	at org.iq80.leveldb.util.LevelIterator.getNextElement(LevelIterator.java:113)
	at org.iq80.leveldb.util.AbstractSeekingIterator.hasNext(AbstractSeekingIterator.java:48)
	at org.iq80.leveldb.util.DbIterator.resetPriorityQueue(DbIterator.java:160)
	at org.iq80.leveldb.util.DbIterator.<init>(DbIterator.java:75)
	at org.iq80.leveldb.impl.DbImpl.internalIterator(DbImpl.java:781)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:747)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:738)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:84)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:65)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:36)
Caused by: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.CompressionType.getCompressionTypeByPersistentId(CompressionType.java:34)
	at org.iq80.leveldb.table.BlockTrailer.readBlockTrailer(BlockTrailer.java:96)
	at org.iq80.leveldb.table.FileChannelTable.readBlock(FileChannelTable.java:58)
	at org.iq80.leveldb.table.Table.<init>(Table.java:61)
	at org.iq80.leveldb.table.FileChannelTable.<init>(FileChannelTable.java:39)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:130)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:114)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:67)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:62)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 17 more
