### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by brunopaiva15** [ljyloo/LevelDb2Avnil#46]
I have this error : Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.ljyloo.PE2PC.ConvertSource.convertSubChunk(ConvertSource.java:127)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:103)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:36)
 
Please help ! :(

**Comment by CodeInspireK6** [comment]
Hi, I'm having an identical error, any guidance would really help!

**Comment by hws689** [comment]
Same issue

**Comment by Karamellwuerfel** [comment]
Same here with 
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
        at java.base/java.lang.System.arraycopy(Native Method)
        at com.ljyloo.PE2PC.ConvertSource.convertSubChunk(ConvertSource.java:127)
        at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:102)
        at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:35)`

**Comment by 0x9fff00** [comment]
This is because of a new subchunk format introduced in Bedrock 1.2.13. (Documentation here: https://gist.github.com/Tomcc/a96af509e275b1af483b25c543cfbf37) This format stores text block IDs instead of numeric IDs, however it does not use blockstates yet. Adding support for this format would require mapping all Bedrock block IDs to Java block IDs (they are different since 1.13), and also mapping Bedrock metadata to blockstates. The blocks would also need to be stored in the new 1.13 format since Update Aquatic blocks have no numeric IDs in Java edition.

**Comment by CrystalRays** [comment]
@0x9fff00 Thanks.I got it.
It seems need tons of work to get fixed. Would you like to work on it?
