### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Mario3264** [ljyloo/LevelDb2Avnil#48]
When I try to convert a world, this happens:

`Exception in thread "main" java.lang.IllegalStateException: CURRENT file does not end with newline
	at org.iq80.leveldb.impl.VersionSet.recover(VersionSet.java:340)
	at org.iq80.leveldb.impl.DbImpl.<init>(DbImpl.java:187)
	at org.iq80.leveldb.impl.Iq80DBFactory.open(Iq80DBFactory.java:71)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:63)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:36)
`

**Comment by Mario3264** [comment]
Closed because it is the same error as Issue #33.
