### ISSUE TITLE
....IllegalArgumentException: Unknown persistentId 4

### ISSUE THREAD

**Issue by snugam** [ljyloo/LevelDb2Avnil#50]
Trying to convert Minecraft PE 1.4.4 world -

Exception in thread "main" org.iq80.leveldb.shaded.guava.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unknown persistentId 4

**Comment by snugam** [comment]
`Exception in thread "main" org.iq80.leveldb.shaded.guava.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.get(LocalCache.java:3937)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.iq80.leveldb.impl.TableCache.getTable(TableCache.java:91)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:79)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:74)
	at org.iq80.leveldb.util.LevelIterator.openNextFile(LevelIterator.java:137)
	at org.iq80.leveldb.util.LevelIterator.getNextElement(LevelIterator.java:113)
	at org.iq80.leveldb.util.AbstractSeekingIterator.hasNext(AbstractSeekingIterator.java:48)
	at org.iq80.leveldb.util.DbIterator.resetPriorityQueue(DbIterator.java:160)
	at org.iq80.leveldb.util.DbIterator.<init>(DbIterator.java:75)
	at org.iq80.leveldb.impl.DbImpl.internalIterator(DbImpl.java:781)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:747)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:738)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:84)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:65)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:36)
Caused by: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.CompressionType.getCompressionTypeByPersistentId(CompressionType.java:34)
	at org.iq80.leveldb.table.BlockTrailer.readBlockTrailer(BlockTrailer.java:96)
	at org.iq80.leveldb.table.MMapTable.readBlock(MMapTable.java:95)
	at org.iq80.leveldb.table.Table.<init>(Table.java:61)
	at org.iq80.leveldb.table.MMapTable.<init>(MMapTable.java:48)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:127)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:114)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:67)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:62)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2197)
`

**Comment by Azim-D3Tm** [comment]
Same here when trying to convert Windows 10 Edition world (generated yesterday)

**Comment by jamese641** [comment]
Same, but being new to this I'm probably doing something very wrong. If anyone knows what please tell me.

Exception in thread "main" org.iq80.leveldb.shaded.guava.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.get(LocalCache.java:3937)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.iq80.leveldb.impl.TableCache.getTable(TableCache.java:91)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:79)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:74)
	at org.iq80.leveldb.util.LevelIterator.openNextFile(LevelIterator.java:137)
	at org.iq80.leveldb.util.LevelIterator.getNextElement(LevelIterator.java:113)
	at org.iq80.leveldb.util.AbstractSeekingIterator.hasNext(AbstractSeekingIterator.java:48)
	at org.iq80.leveldb.util.DbIterator.resetPriorityQueue(DbIterator.java:160)
	at org.iq80.leveldb.util.DbIterator.<init>(DbIterator.java:75)
	at org.iq80.leveldb.impl.DbImpl.internalIterator(DbImpl.java:781)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:747)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:738)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:84)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:85)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:62)
Caused by: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.CompressionType.getCompressionTypeByPersistentId(CompressionType.java:34)
	at org.iq80.leveldb.table.BlockTrailer.readBlockTrailer(BlockTrailer.java:96)
	at org.iq80.leveldb.table.MMapTable.readBlock(MMapTable.java:95)
	at org.iq80.leveldb.table.Table.<init>(Table.java:61)
	at org.iq80.leveldb.table.MMapTable.<init>(MMapTable.java:48)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:127)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:114)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:67)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:62)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2197)
