### ISSUE TITLE
Done! with no files

### ISSUE THREAD

**Issue by koredesigngroup** [ljyloo/LevelDb2Avnil#59]
Hi everyone, crazy how this app is still in use! Can you guys just convert my world for me? I've spent a few days troubleshooting with no luck. I get a bunch of exception errors on Mac and a Done! message in windows with no actual files.

My file: https://www.dropbox.com/sh/j72tykguvqxxgo8/AABtkqSUALG99J0D7CdB8WpTa?dl=0

Thank you in advance!

@ljyloo 

screenshot for windows: https://www.dropbox.com/s/ph4wau3s17vlqu9/Screenshot%202020-04-21%2012.02.21.png?dl=0

**Comment by koredesigngroup** [comment]
errors on mac:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.iq80.leveldb.util.ByteBufferSupport (file:/Users/carbalo/Desktop/MineConvert-master/LevelDBtoAnvil/Converter.jar) to method sun.nio.ch.FileChannelImpl.unmap(java.nio.MappedByteBuffer)
WARNING: Please consider reporting this to the maintainers of org.iq80.leveldb.util.ByteBufferSupport
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" org.iq80.leveldb.shaded.guava.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.get(LocalCache.java:3937)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.iq80.leveldb.impl.TableCache.getTable(TableCache.java:91)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:79)
	at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:74)
	at org.iq80.leveldb.impl.Version.getLevel0Files(Version.java:146)
	at org.iq80.leveldb.impl.DbImpl.internalIterator(DbImpl.java:781)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:747)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:738)
	at org.iq80.leveldb.impl.DbImpl.iterator(DbImpl.java:84)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:85)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:62)
Caused by: java.lang.IllegalArgumentException: Unknown persistentId 4
	at org.iq80.leveldb.CompressionType.getCompressionTypeByPersistentId(CompressionType.java:34)
	at org.iq80.leveldb.table.BlockTrailer.readBlockTrailer(BlockTrailer.java:96)
	at org.iq80.leveldb.table.MMapTable.readBlock(MMapTable.java:95)
	at org.iq80.leveldb.table.Table.<init>(Table.java:61)
	at org.iq80.leveldb.table.MMapTable.<init>(MMapTable.java:48)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:127)
	at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:114)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:67)
	at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:62)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at org.iq80.leveldb.shaded.guava.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 13 more
