### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ghost** [ljyloo/LevelDb2Avnil#61]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.ljyloo.PE2PC.ConvertSource.convertSubChunk(ConvertSource.java:127)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:102)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:35)

**Comment by ljyloo** [comment]
This converter only works on maps from some specific versions of MCPE...
Trying to feed maps generated from not supported version of MCPE into the converter will usually cause such a problem.
Maybe you can attach the infomation of your maps and I'll take a look
